=begin html

<h1>Giblog - Website and Blog builder</h1>

Giblog is Website and Blog builder written by Perl.

<h2>Website Example</h2>

This is Website initial example.

<a href="https://new-website-example.giblog.net/">Website Example</a><br><br>

<a href="https://new-website-example.giblog.net/"><img src="/images/giblog-website.png" style="widht:98%;border:1px solid #ddd"></a><br>

<h2>Blog Example</h2>

This is Blog initial example.

<a href="https://new-blog-example.giblog.net/">Blog Example</a><br><br>

<a href="https://new-blog-example.giblog.net/"><img src="/images/giblog-blog.png" style="widht:98%;border:1px solid #ddd"></a><br><br>

<h2>Information Site Example</h2>

This is Information site example.

<a href="https://tutorial.perlzemi.com/">Information Site Example</a><br><br>

<a href="https://tutorial.perlzemi.com/"><img src="/images/perlzemi.png" style="widht:98%;border:1px solid #ddd"></a><br><br>

<b>Do you need to create personal site or blog, or corporate site or blog?</b><br><br>

If you are so, let's read the following description, features, tutorials.

=end html

=head1 DESCRIPTION

Giblog is B<Website and Blog builder> written by Perl.

You can create B<your website and blog> easily.

All created files is B<static HTML>, so you can manage them using B<git>.

You can B<customize your website by Perl>.

Giblog is in beta test before 1.0 release. Note that features is changed without warnings.

=head1 SYNOPSYS
  
  # New empty web site
  giblog new mysite

  # New web site
  giblog new_website mysite

  # New blog
  giblog new_blog mysite
  
  # Change directory
  cd mysite
  
  # Add new entry
  giblog add

  # Build web site
  giblog build
  
  # Serve web site(need Mojolicious)
  morbo serve.pl

  # Add new entry with home directory
  giblog add --home /home/kimoto/mysite
  
  # Build web site with home directory
  giblog build --home /home/kimoto/mysite

=head1 FEATURES

Giblog have the following features.

=over 4

=item * Build Website and Blog.

=item * Linux, Mac OS, Windows Support. (In Windows, recommend installation of msys2)

=item * Responsive web site support. Default CSS is setup for PC and Smart phone.

=item * Header, Hooter and Side bar support

=item * You can customize Top and Bottom section of content.

=item * Automatical Line break. p tag is automatically added.

=item * Escape E<lt>, E<gt> automatically in pre tag

=item * Title tag is automatically added from first h1-h6 tag.

=item * Description meta tag is automatically added from first p tag.

=item * You can customize your web site by Perl programming laugnage.

=item * You can serve your web site in local environment. Contents changes is detected and build automatically(need L<Mojolicious>).

=item * Build 645 pages by 0.78 seconds in starndard linux environment.

=item * All build files is Static. you can manage files by Git.

=back

=head1 TUTORIAL

=head2 Create web site

B<1. Empty website>

"new" command create empty website. "mysite" is a name of your web site.

  giblog new mysite

If you want to create empty site, choice this command.

Templates and CSS is empty and provide minimal build script.

B<2. Website>

"new_website" command create simple website.  "mysite" is a name of your web site.

  giblog new_website mysite

If you want to create simple website, choice this command.

Top page "templates/index.html" is created. CSS supports responsive design and provide basic build script.

B<3. Blog>

"new_blog" command create empty website.  "mysite" is a name of your web site.

  giblog new_blog mysite

If you want to create blog, choice this prototype.

Top page "templates/index.html" is created, which show 7 days entries.

List page "templates/list.html" is created, which show all entries links.

CSS supports responsive design and provide basic build script.

=head2 Add entry page

You need to change directory to "mysite" before run "add" command if you are in other directory.

  cd mysite

"add" command add entry page.
  
  giblog add

Created file name is, for example,

  templates/blog/20080108132865.html

This file name contains current date and time.

=head2 Build web site

You need to change directory to "mysite" before run "build" command if you are in other directory.

  cd mysite

"build" command build web site.

  giblog build

What is build process?

Build script is writen in "lib/Giblog/Command/build.pm".

"build" command only execute "run" method in "Giblog::Command::build.pm" .

  # "lib/Giblog/Command/build.pm" in web site created by "new_blog" command
  package Giblog::Command::build;

  use base 'Giblog::Command';

  use strict;
  use warnings;

  use File::Basename 'basename';

  sub run {
    my ($self, @args) = @_;
    
    # API
    my $api = $self->api;
    
    # Read config
    my $config = $api->read_config;
    
    # Copy static files to public
    $api->copy_static_files_to_public;

    # Get files in templates directory
    my $files = $api->get_templates_files;
    
    for my $file (@$files) {
      # Data
      my $data = {file => $file};
      
      # Get content from file in templates directory
      $api->get_content($data);

      # Parse Giblog syntax
      $api->parse_giblog_syntax($data);

      # Parse title
      $api->parse_title_from_first_h_tag($data);

      # Edit title
      my $site_title = $config->{site_title};
      if ($data->{file} eq 'index.html') {
        $data->{title} = $site_title;
      }
      else {
        $data->{title} = "$data->{title} - $site_title";
      }

      # Add page link
      $api->add_page_link_to_first_h_tag($data, {root => 'index.html'});

      # Parse description
      $api->parse_description_from_first_p_tag($data);

      # Read common templates
      $api->read_common_templates($data);
      
      # Add meta title
      $api->add_meta_title($data);

      # Add meta description
      $api->add_meta_description($data);

      # Build entry html
      $api->build_entry($data);
      
      # Build whole html
      $api->build_html($data);
      
      # Write to public file
      $api->write_to_public_file($data);
    }
    
    # Create index page
    $self->create_index;
    
    # Create list page
    $self->create_list;
  }

You can customize build script if you need.

If you need to know Giblog API, see L<Giblog::API>.

=head2 Serve web site

If you have L<Mojolicious>, you can serve web site in local environment.

   morbo serve.pl

You see the following message.

   Server available at http://127.0.0.1:3000
   Server start

If files in "templates" directory is changed, Web site is automatically rebuild.

=head1 METHODS

These methods is internally methods.
Normally, you don't need to know these methods.
See L<Giblog::API> to manipulate HTML contents.

=head2 new

  my $api = Giblog->new(%params);

Create L<Giblog> object.

B<Parameters:>

=over 4

=item * home_dir - home directory

=item * config - config

=back

=head2 run_command

  $giblog->run_command(@argv);

Run command system.

=head2 config

  my $config = $giblog->config;

Get Giblog config.

=head2 home_dir

  my $home_dir = $giblog->home_dir;

Get home directory.

=head1 AUTHOR

Yuki Kimoto, C<< <kimoto.yuki at gmail.com> >>

=head1 LICENSE AND COPYRIGHT

Copyright 2018-2019 Yuki Kimoto.

This program is free software; you can redistribute it and/or modify it
under the terms of the the Artistic License (2.0). You may obtain a
copy of the full license at:

L<http://www.perlfoundation.org/artistic_license_2_0>

=cut

1;
