#!perl

use strict;
use warnings;

use Giblog;
use Giblog::API;

my $opt = Giblog->parse_argv(@ARGV);

my $command_name = $opt->{command_name};
my $argv = $opt->{argv};

my $api = Giblog->build_api(%$opt);

$api->run_command($command_name, @$argv);
