#!perl

use strict;
use warnings;

use Giblog;

Giblog->run_command(@ARGV);

=encoding utf8

=head1 NAME

giblog - giblog command

=head1 SYNOPSIS

  Usage: giblog [OPTIONS] [COMMAND] [ARGS]

    giblog new mysite
    giblog new_website mysite
    giblog new_blog mysite
    giblog add
    giblog build
    giblog -C /home/kimoto/mysite add
    giblog -H /home/kimoto/mysite add
    giblog --home /home/kimoto/mysite build

  Options:
    -C, -H, --home <directory>     Home directory
    -h, --help                     Show this message

=head1 DESCRIPTION

Run Giblog command which is implemented as subclass of L<Giblog::Command>.

=cut
