#!perl

use strict;
use warnings;

use Giblog;

my $giblog = Giblog->new;

# Command
my $command = shift;
unless (defined $command) {
  die "Command must be specifed\n";
}
if ($command =~ /^-/) {
  die "Command \"$command\" is not found\n";
}

# Create new website
if ($command eq 'new_website') {
  my $website_name = shift;
  
  $giblog->new_website($website_name);
}
elsif ($command eq 'new_entry') {
  $giblog->new_entry;
}
else {
  die "Command \"$command\" is not found\n";
}
